---
title: "rem-spp"
author: "Mitch Porter"
date: "2024-03-25"
output: html_document
---

```{r setup, include=FALSE}
rem9 <- colnames(net9_ES[[118]])
rem10 <- colnames(net10_ES[[152]])
rem11 <- colnames(net11_ES[[64]])
```

```{r}
prov_rem9 <- rem9[! rem9 %in% other]
prov_rem9 <- prov_rem9[! prov_rem9 %in% ES]

prov_rem10 <- rem10[! rem10 %in% other]
prov_rem10 <- prov_rem10[! prov_rem10 %in% ES]

prov_rem11 <- rem11[! rem11 %in% other]
prov_rem11 <- prov_rem11[! prov_rem11 %in% ES]
```

```{r}
other_rem9 <- rem9[! rem9 %in% providers]
other_rem9 <- other_rem9[! other_rem9 %in% ES]

other_rem10 <- rem10[! rem10 %in% providers]
other_rem10 <- other_rem10[! other_rem10 %in% ES]

other_rem11 <- rem11[! rem11 %in% providers]
other_rem11 <- other_rem11[! other_rem11 %in% ES]
```

```{r}
prov_rem9_prop <- length(prov_rem9)/length(providers)
prov_rem10_prop <- length(prov_rem10)/length(providers)
prov_rem11_prop <- length(prov_rem11)/length(providers)

other_rem9_prop <- length(other_rem9)/length(other)
other_rem10_prop <- length(other_rem10)/length(other)
other_rem11_prop <- length(other_rem11)/length(other)

header <- c("Sequence 9","Sequence 9","Sequence 10","Sequence 10","Sequence 11","Sequence 11")
Sequence <- c("ESPs", "Other", "ESPs", "Other", "ESPs", "Other")
prop <- c(prov_rem9_prop,other_rem9_prop,prov_rem10_prop,other_rem10_prop,prov_rem11_prop,other_rem11_prop)
rem <- data.frame(header, Sequence, prop)

ggplot(rem, aes(fill=Sequence, y=prop, x=header)) + 
    geom_bar(position="dodge", stat="identity") + ylab("Proportion remaining") + xlab(NULL) + theme_classic() + scale_fill_manual(values=c("#028b8b", "#02cdce"))
```

