---
title: "rb-es-indiv"
author: "Mitch Porter"
date: "2024-03-08"
output: html_document
---

```{r setup, include=FALSE}
#load packages
library(igraph)
library(tidyverse)
library(multiweb)
library(DescTools)
library(ggplot2)
library(NetIndices)

#load data
load("./seq1-3.RData")
load("./seq4-11.RData")
nodes <- read.csv("./nodes.csv")
links <- read.csv("./links.csv")
```

```{r}
#track ES loss for each sequence

#FI
stats_FI4 <- data.frame()
for (i in 1:length(net4_ES)){
  species <- as.data.frame(net4_ES[[i]])
  species <- names(species)
  FI <- c("Fisheries")
  species_diff <- intersect(FI,species)
  ES_lost <- (length(FI)-length(species_diff))
  stats_FI4 <- rbind(stats_FI4, ES_lost)
}

stats_FI4$pri_ext <- 1:nrow(stats_FI4)
num <- count(stats_FI4)
num <- as.integer(num)
stats_FI4$n <- num - stats_FI4$pri_ext

stats_FI4 <- top_n(stats_FI4, nrow(stats_spp4), n)

stats_FI5 <- data.frame()
for (i in 1:length(net5_ES)){
  species <- as.data.frame(net5_ES[[i]])
  species <- names(species)
  FI <- c("Fisheries")
  species_diff <- intersect(FI,species)
  ES_lost <- (length(FI)-length(species_diff))
  stats_FI5 <- rbind(stats_FI5, ES_lost)
}

stats_FI5$pri_ext <- 1:nrow(stats_FI5)
num <- count(stats_FI5)
num <- as.integer(num)
stats_FI5$n <- num - stats_FI5$pri_ext

stats_FI5 <- top_n(stats_FI5, nrow(stats_spp5), n)

stats_FI6 <- data.frame()
for (i in 1:length(net6_ES)){
  species <- as.data.frame(net6_ES[[i]])
  species <- names(species)
  FI <- c("Fisheries")
  species_diff <- intersect(FI,species)
  ES_lost <- (length(FI)-length(species_diff))
  stats_FI6 <- rbind(stats_FI6, ES_lost)
}

stats_FI6$pri_ext <- 1:nrow(stats_FI6)
num <- count(stats_FI6)
num <- as.integer(num)
stats_FI6$n <- num - stats_FI6$pri_ext

stats_FI6 <- top_n(stats_FI6, nrow(stats_spp6), n)

stats_FI7 <- data.frame()
for (i in 1:length(net7_ES)){
  species <- as.data.frame(net7_ES[[i]])
  species <- names(species)
  FI <- c("Fisheries")
  species_diff <- intersect(FI,species)
  ES_lost <- (length(FI)-length(species_diff))
  stats_FI7 <- rbind(stats_FI7, ES_lost)
}

stats_FI7$pri_ext <- 1:nrow(stats_FI7)
num <- count(stats_FI7)
num <- as.integer(num)
stats_FI7$n <- num - stats_FI7$pri_ext

stats_FI7 <- top_n(stats_FI7, nrow(stats_spp7), n)

stats_FI8 <- data.frame()
for (i in 1:length(net8_ES)){
  species <- as.data.frame(net8_ES[[i]])
  species <- names(species)
  FI <- c("Fisheries")
  species_diff <- intersect(FI,species)
  ES_lost <- (length(FI)-length(species_diff))
  stats_FI8 <- rbind(stats_FI8, ES_lost)
}

stats_FI8$pri_ext <- 1:nrow(stats_FI8)
num <- count(stats_FI8)
num <- as.integer(num)
stats_FI8$n <- num - stats_FI8$pri_ext

stats_FI8 <- top_n(stats_FI8, 82, n)

stats_FI9 <- data.frame()
for (i in 1:length(net9_ES)){
  species <- as.data.frame(net9_ES[[i]])
  species <- names(species)
  FI <- c("Fisheries")
  species_diff <- intersect(FI,species)
  ES_lost <- (length(FI)-length(species_diff))
  stats_FI9 <- rbind(stats_FI9, ES_lost)
}

stats_FI9$pri_ext <- 1:nrow(stats_FI9)
num <- count(stats_FI9)
num <- as.integer(num)
stats_FI9$n <- num - stats_FI9$pri_ext

stats_FI9 <- top_n(stats_FI9, 140, n)

stats_FI10 <- data.frame()
for (i in 1:length(net10_ES)){
  species <- as.data.frame(net10_ES[[i]])
  species <- names(species)
  FI <- c("Fisheries")
  species_diff <- intersect(FI,species)
  ES_lost <- (length(FI)-length(species_diff))
  stats_FI10 <- rbind(stats_FI10, ES_lost)
}

stats_FI10$pri_ext <- 1:nrow(stats_FI10)
num <- count(stats_FI10)
num <- as.integer(num)
stats_FI10$n <- num - stats_FI10$pri_ext

stats_FI10 <- top_n(stats_FI10, 156, n)

stats_FI11 <- data.frame()
for (i in 1:length(net11_ES)){
  species <- as.data.frame(net11_ES[[i]])
  species <- names(species)
  FI <- c("Fisheries")
  species_diff <- intersect(FI,species)
  ES_lost <- (length(FI)-length(species_diff))
  stats_FI11 <- rbind(stats_FI11, ES_lost)
}

stats_FI11$pri_ext <- 1:nrow(stats_FI11)
num <- count(stats_FI11)
num <- as.integer(num)
stats_FI11$n <- num - stats_FI11$pri_ext

stats_FI11 <- top_n(stats_FI11, 115, n)

#RM
stats_RM4 <- data.frame()
for (i in 1:length(net4_ES)){
  species <- as.data.frame(net4_ES[[i]])
  species <- names(species)
  RM <- c("RawMat")
  species_diff <- intersect(RM,species)
  ES_lost <- (length(RM)-length(species_diff))
  stats_RM4 <- rbind(stats_RM4, ES_lost)
}

stats_RM4$pri_ext <- 1:nrow(stats_RM4)
num <- count(stats_RM4)
num <- as.integer(num)
stats_RM4$n <- num - stats_RM4$pri_ext

stats_RM4 <- top_n(stats_RM4, nrow(stats_spp4), n)

stats_RM5 <- data.frame()
for (i in 1:length(net5_ES)){
  species <- as.data.frame(net5_ES[[i]])
  species <- names(species)
  RM <- c("RawMat")
  species_diff <- intersect(RM,species)
  ES_lost <- (length(RM)-length(species_diff))
  stats_RM5 <- rbind(stats_RM5, ES_lost)
}

stats_RM5$pri_ext <- 1:nrow(stats_RM5)
num <- count(stats_RM5)
num <- as.integer(num)
stats_RM5$n <- num - stats_RM5$pri_ext

stats_RM5 <- top_n(stats_RM5, nrow(stats_spp5), n)

stats_RM6 <- data.frame()
for (i in 1:length(net6_ES)){
  species <- as.data.frame(net6_ES[[i]])
  species <- names(species)
  RM <- c("RawMat")
  species_diff <- intersect(RM,species)
  ES_lost <- (length(RM)-length(species_diff))
  stats_RM6 <- rbind(stats_RM6, ES_lost)
}

stats_RM6$pri_ext <- 1:nrow(stats_RM6)
num <- count(stats_RM6)
num <- as.integer(num)
stats_RM6$n <- num - stats_RM6$pri_ext

stats_RM6 <- top_n(stats_RM6, nrow(stats_spp6), n)

stats_RM7 <- data.frame()
for (i in 1:length(net7_ES)){
  species <- as.data.frame(net7_ES[[i]])
  species <- names(species)
  RM <- c("RawMat")
  species_diff <- intersect(RM,species)
  ES_lost <- (length(RM)-length(species_diff))
  stats_RM7 <- rbind(stats_RM7, ES_lost)
}

stats_RM7$pri_ext <- 1:nrow(stats_RM7)
num <- count(stats_RM7)
num <- as.integer(num)
stats_RM7$n <- num - stats_RM7$pri_ext

stats_RM7 <- top_n(stats_RM7, nrow(stats_spp7), n)

stats_RM8 <- data.frame()
for (i in 1:length(net8_ES)){
  species <- as.data.frame(net8_ES[[i]])
  species <- names(species)
  RM <- c("RawMat")
  species_diff <- intersect(RM,species)
  ES_lost <- (length(RM)-length(species_diff))
  stats_RM8 <- rbind(stats_RM8, ES_lost)
}

stats_RM8$pri_ext <- 1:nrow(stats_RM8)
num <- count(stats_RM8)
num <- as.integer(num)
stats_RM8$n <- num - stats_RM8$pri_ext

stats_RM8 <- top_n(stats_RM8, 82, n)

stats_RM9 <- data.frame()
for (i in 1:length(net9_ES)){
  species <- as.data.frame(net9_ES[[i]])
  species <- names(species)
  RM <- c("RawMat")
  species_diff <- intersect(RM,species)
  ES_lost <- (length(RM)-length(species_diff))
  stats_RM9 <- rbind(stats_RM9, ES_lost)
}

stats_RM9$pri_ext <- 1:nrow(stats_RM9)
num <- count(stats_RM9)
num <- as.integer(num)
stats_RM9$n <- num - stats_RM9$pri_ext

stats_RM9 <- top_n(stats_RM9, 140, n)

stats_RM10 <- data.frame()
for (i in 1:length(net10_ES)){
  species <- as.data.frame(net10_ES[[i]])
  species <- names(species)
  RM <- c("RawMat")
  species_diff <- intersect(RM,species)
  ES_lost <- (length(RM)-length(species_diff))
  stats_RM10 <- rbind(stats_RM10, ES_lost)
}

stats_RM10$pri_ext <- 1:nrow(stats_RM10)
num <- count(stats_RM10)
num <- as.integer(num)
stats_RM10$n <- num - stats_RM10$pri_ext

stats_RM10 <- top_n(stats_RM10, 156, n)

stats_RM11 <- data.frame()
for (i in 1:length(net11_ES)){
  species <- as.data.frame(net11_ES[[i]])
  species <- names(species)
  RM <- c("RawMat")
  species_diff <- intersect(RM,species)
  ES_lost <- (length(RM)-length(species_diff))
  stats_RM11 <- rbind(stats_RM11, ES_lost)
}

stats_RM11$pri_ext <- 1:nrow(stats_RM11)
num <- count(stats_RM11)
num <- as.integer(num)
stats_RM11$n <- num - stats_RM11$pri_ext

stats_RM11 <- top_n(stats_RM11, 115, n)


#HF
stats_HF4 <- data.frame()
for (i in 1:length(net4_ES)){
  species <- as.data.frame(net4_ES[[i]])
  species <- names(species)
HF <- c("HabitatForm")
  species_diff <- intersect(HF,species)
  ES_lost <- (length(HF)-length(species_diff))
  stats_HF4 <- rbind(stats_HF4, ES_lost)
}

stats_HF4$pri_ext <- 1:nrow(stats_HF4)
num <- count(stats_HF4)
num <- as.integer(num)
stats_HF4$n <- num - stats_HF4$pri_ext

stats_HF4 <- top_n(stats_HF4, nrow(stats_spp4), n)

stats_HF5 <- data.frame()
for (i in 1:length(net5_ES)){
  species <- as.data.frame(net5_ES[[i]])
  species <- names(species)
  HF <- c("HabitatForm")
  species_diff <- intersect(HF,species)
  ES_lost <- (length(HF)-length(species_diff))
  stats_HF5 <- rbind(stats_HF5, ES_lost)
}

stats_HF5$pri_ext <- 1:nrow(stats_HF5)
num <- count(stats_HF5)
num <- as.integer(num)
stats_HF5$n <- num - stats_HF5$pri_ext

stats_HF5 <- top_n(stats_HF5, nrow(stats_spp5), n)

stats_HF6 <- data.frame()
for (i in 1:length(net6_ES)){
  species <- as.data.frame(net6_ES[[i]])
  species <- names(species)
  HF <- c("HabitatForm")
  species_diff <- intersect(HF,species)
  ES_lost <- (length(HF)-length(species_diff))
  stats_HF6 <- rbind(stats_HF6, ES_lost)
}

stats_HF6$pri_ext <- 1:nrow(stats_HF6)
num <- count(stats_HF6)
num <- as.integer(num)
stats_HF6$n <- num - stats_HF6$pri_ext

stats_HF6 <- top_n(stats_HF6, nrow(stats_spp6), n)

stats_HF7 <- data.frame()
for (i in 1:length(net7_ES)){
  species <- as.data.frame(net7_ES[[i]])
  species <- names(species)
  HF <- c("HabitatForm")
  species_diff <- intersect(HF,species)
  ES_lost <- (length(HF)-length(species_diff))
  stats_HF7 <- rbind(stats_HF7, ES_lost)
}

stats_HF7$pri_ext <- 1:nrow(stats_HF7)
num <- count(stats_HF7)
num <- as.integer(num)
stats_HF7$n <- num - stats_HF7$pri_ext

stats_HF7 <- top_n(stats_HF7, nrow(stats_spp7), n)

stats_HF8 <- data.frame()
for (i in 1:length(net8_ES)){
  species <- as.data.frame(net8_ES[[i]])
  species <- names(species)
  HF <- c("HabitatForm")
  species_diff <- intersect(HF,species)
  ES_lost <- (length(HF)-length(species_diff))
  stats_HF8 <- rbind(stats_HF8, ES_lost)
}

stats_HF8$pri_ext <- 1:nrow(stats_HF8)
num <- count(stats_HF8)
num <- as.integer(num)
stats_HF8$n <- num - stats_HF8$pri_ext

stats_HF8 <- top_n(stats_HF8, 82, n)

stats_HF9 <- data.frame()
for (i in 1:length(net9_ES)){
  species <- as.data.frame(net9_ES[[i]])
  species <- names(species)
  HF <- c("HabitatForm")
  species_diff <- intersect(HF,species)
  ES_lost <- (length(HF)-length(species_diff))
  stats_HF9 <- rbind(stats_HF9, ES_lost)
}

stats_HF9$pri_ext <- 1:nrow(stats_HF9)
num <- count(stats_HF9)
num <- as.integer(num)
stats_HF9$n <- num - stats_HF9$pri_ext

stats_HF9 <- top_n(stats_HF9, 140, n)

stats_HF10 <- data.frame()
for (i in 1:length(net10_ES)){
  species <- as.data.frame(net10_ES[[i]])
  species <- names(species)
  HF <- c("HabitatForm")
  species_diff <- intersect(HF,species)
  ES_lost <- (length(HF)-length(species_diff))
  stats_HF10 <- rbind(stats_HF10, ES_lost)
}

stats_HF10$pri_ext <- 1:nrow(stats_HF10)
num <- count(stats_HF10)
num <- as.integer(num)
stats_HF10$n <- num - stats_HF10$pri_ext

stats_HF10 <- top_n(stats_HF10, 156, n)

stats_HF11 <- data.frame()
for (i in 1:length(net11_ES)){
  species <- as.data.frame(net11_ES[[i]])
  species <- names(species)
  HF <- c("HabitatForm")
  species_diff <- intersect(HF,species)
  ES_lost <- (length(HF)-length(species_diff))
  stats_HF11 <- rbind(stats_HF11, ES_lost)
}
stats_HF11$pri_ext <- 1:nrow(stats_HF11)
num <- count(stats_HF11)
num <- as.integer(num)
stats_HF11$n <- num - stats_HF11$pri_ext

stats_HF11 <- top_n(stats_HF11, 115, n)


#BP
stats_BP4 <- data.frame()
for (i in 1:length(net4_ES)){
  species <- as.data.frame(net4_ES[[i]])
  species <- names(species)
  BP <- c("Biopurification")
  species_diff <- intersect(BP,species)
  ES_lost <- (length(BP)-length(species_diff))
  stats_BP4 <- rbind(stats_BP4, ES_lost)
}

stats_BP4$pri_ext <- 1:nrow(stats_BP4)
num <- count(stats_BP4)
num <- as.integer(num)
stats_BP4$n <- num - stats_BP4$pri_ext

stats_BP4 <- top_n(stats_BP4, nrow(stats_spp4), n)

stats_BP5 <- data.frame()
for (i in 1:length(net5_ES)){
  species <- as.data.frame(net5_ES[[i]])
  species <- names(species)
  BP <- c("Biopurification")
  species_diff <- intersect(BP,species)
  ES_lost <- (length(BP)-length(species_diff))
  stats_BP5 <- rbind(stats_BP5, ES_lost)
}

stats_BP5$pri_ext <- 1:nrow(stats_BP5)
num <- count(stats_BP5)
num <- as.integer(num)
stats_BP5$n <- num - stats_BP5$pri_ext

stats_BP5 <- top_n(stats_BP5, nrow(stats_spp5), n)

stats_BP6 <- data.frame()
for (i in 1:length(net6_ES)){
  species <- as.data.frame(net6_ES[[i]])
  species <- names(species)
  BP <- c("Biopurification")
  species_diff <- intersect(BP,species)
  ES_lost <- (length(BP)-length(species_diff))
  stats_BP6 <- rbind(stats_BP6, ES_lost)
}

stats_BP6$pri_ext <- 1:nrow(stats_BP6)
num <- count(stats_BP6)
num <- as.integer(num)
stats_BP6$n <- num - stats_BP6$pri_ext

stats_BP6 <- top_n(stats_BP6, nrow(stats_spp6), n)

stats_BP7 <- data.frame()
for (i in 1:length(net7_ES)){
  species <- as.data.frame(net7_ES[[i]])
  species <- names(species)
  BP <- c("Biopurification")
  species_diff <- intersect(BP,species)
  ES_lost <- (length(BP)-length(species_diff))
  stats_BP7 <- rbind(stats_BP7, ES_lost)
}

stats_BP7$pri_ext <- 1:nrow(stats_BP7)
num <- count(stats_BP7)
num <- as.integer(num)
stats_BP7$n <- num - stats_BP7$pri_ext

stats_BP7 <- top_n(stats_BP7, nrow(stats_spp7), n)

stats_BP8 <- data.frame()
for (i in 1:length(net8_ES)){
  species <- as.data.frame(net8_ES[[i]])
  species <- names(species)
  BP <- c("Biopurification")
  species_diff <- intersect(BP,species)
  ES_lost <- (length(BP)-length(species_diff))
  stats_BP8 <- rbind(stats_BP8, ES_lost)
}

stats_BP8$pri_ext <- 1:nrow(stats_BP8)
num <- count(stats_BP8)
num <- as.integer(num)
stats_BP8$n <- num - stats_BP8$pri_ext

stats_BP8 <- top_n(stats_BP8, 82, n)

stats_BP9 <- data.frame()
for (i in 1:length(net9_ES)){
  species <- as.data.frame(net9_ES[[i]])
  species <- names(species)
  BP <- c("Biopurification")
  species_diff <- intersect(BP,species)
  ES_lost <- (length(BP)-length(species_diff))
  stats_BP9 <- rbind(stats_BP9, ES_lost)
}

stats_BP9$pri_ext <- 1:nrow(stats_BP9)
num <- count(stats_BP9)
num <- as.integer(num)
stats_BP9$n <- num - stats_BP9$pri_ext

stats_BP9 <- top_n(stats_BP9, 140, n)

stats_BP10 <- data.frame()
for (i in 1:length(net10_ES)){
  species <- as.data.frame(net10_ES[[i]])
  species <- names(species)
  BP <- c("Biopurification")
  species_diff <- intersect(BP,species)
  ES_lost <- (length(BP)-length(species_diff))
  stats_BP10 <- rbind(stats_BP10, ES_lost)
}

stats_BP10$pri_ext <- 1:nrow(stats_BP10)
num <- count(stats_BP10)
num <- as.integer(num)
stats_BP10$n <- num - stats_BP10$pri_ext

stats_BP10 <- top_n(stats_BP10, 156, n)

stats_BP11 <- data.frame()
for (i in 1:length(net11_ES)){
  species <- as.data.frame(net11_ES[[i]])
  species <- names(species)
  BP <- c("Biopurification")
  species_diff <- intersect(BP,species)
  ES_lost <- (length(BP)-length(species_diff))
  stats_BP11 <- rbind(stats_BP11, ES_lost)
}

stats_BP11$pri_ext <- 1:nrow(stats_BP11)
num <- count(stats_BP11)
num <- as.integer(num)
stats_BP11$n <- num - stats_BP11$pri_ext

stats_BP11 <- top_n(stats_BP11, 115, n)

#CC
stats_CC4 <- data.frame()
for (i in 1:length(net4_ES)){
  species <- as.data.frame(net4_ES[[i]])
  species <- names(species)
  CC <- c("Ccycling")
  species_diff <- intersect(CC,species)
  ES_lost <- (length(CC)-length(species_diff))
  stats_CC4 <- rbind(stats_CC4, ES_lost)
}

stats_CC4$pri_ext <- 1:nrow(stats_CC4)
num <- count(stats_CC4)
num <- as.integer(num)
stats_CC4$n <- num - stats_CC4$pri_ext

stats_CC4 <- top_n(stats_CC4, nrow(stats_spp4), n)

stats_CC5 <- data.frame()
for (i in 1:length(net5_ES)){
  species <- as.data.frame(net5_ES[[i]])
  species <- names(species)
  CC <- c("Ccycling")
  species_diff <- intersect(CC,species)
  ES_lost <- (length(CC)-length(species_diff))
  stats_CC5 <- rbind(stats_CC5, ES_lost)
}

stats_CC5$pri_ext <- 1:nrow(stats_CC5)
num <- count(stats_CC5)
num <- as.integer(num)
stats_CC5$n <- num - stats_CC5$pri_ext

stats_CC5 <- top_n(stats_CC5, nrow(stats_spp5), n)

stats_CC6 <- data.frame()
for (i in 1:length(net6_ES)){
  species <- as.data.frame(net6_ES[[i]])
  species <- names(species)
  CC <- c("Ccycling")
  species_diff <- intersect(CC,species)
  ES_lost <- (length(CC)-length(species_diff))
  stats_CC6 <- rbind(stats_CC5, ES_lost)
}

stats_CC6$pri_ext <- 1:nrow(stats_CC6)
num <- count(stats_CC6)
num <- as.integer(num)
stats_CC6$n <- num - stats_CC6$pri_ext

stats_CC6 <- top_n(stats_CC6, nrow(stats_spp6), n)

stats_CC7 <- data.frame()
for (i in 1:length(net7_ES)){
  species <- as.data.frame(net7_ES[[i]])
  species <- names(species)
  CC <- c("Ccycling")
  species_diff <- intersect(CC,species)
  ES_lost <- (length(CC)-length(species_diff))
  stats_CC7 <- rbind(stats_CC7, ES_lost)
}

stats_CC7$pri_ext <- 1:nrow(stats_CC7)
num <- count(stats_CC7)
num <- as.integer(num)
stats_CC7$n <- num - stats_CC7$pri_ext

stats_CC7 <- top_n(stats_CC7, nrow(stats_spp7), n)

stats_CC8 <- data.frame()
for (i in 1:length(net8_ES)){
  species <- as.data.frame(net8_ES[[i]])
  species <- names(species)
  CC <- c("Ccycling")
  species_diff <- intersect(CC,species)
  ES_lost <- (length(CC)-length(species_diff))
  stats_CC8 <- rbind(stats_CC8, ES_lost)
}

stats_CC8$pri_ext <- 1:nrow(stats_CC8)
num <- count(stats_CC8)
num <- as.integer(num)
stats_CC8$n <- num - stats_CC8$pri_ext

stats_CC8 <- top_n(stats_CC8, 82, n)

stats_CC9 <- data.frame()
for (i in 1:length(net9_ES)){
  species <- as.data.frame(net9_ES[[i]])
  species <- names(species)
  CC <- c("Ccycling")
  species_diff <- intersect(CC,species)
  ES_lost <- (length(CC)-length(species_diff))
  stats_CC9 <- rbind(stats_CC9, ES_lost)
}

stats_CC9$pri_ext <- 1:nrow(stats_CC9)
num <- count(stats_CC9)
num <- as.integer(num)
stats_CC9$n <- num - stats_CC9$pri_ext

stats_CC9 <- top_n(stats_CC9, 140, n)

stats_CC10 <- data.frame()
for (i in 1:length(net10_ES)){
  species <- as.data.frame(net10_ES[[i]])
  species <- names(species)
  CC <- c("Ccycling")
  species_diff <- intersect(CC,species)
  ES_lost <- (length(CC)-length(species_diff))
  stats_CC10 <- rbind(stats_CC10, ES_lost)
}

stats_CC10$pri_ext <- 1:nrow(stats_CC10)
num <- count(stats_CC10)
num <- as.integer(num)
stats_CC10$n <- num - stats_CC10$pri_ext

stats_CC10 <- top_n(stats_CC10, 156, n)

stats_CC11 <- data.frame()
for (i in 1:length(net11_ES)){
  species <- as.data.frame(net11_ES[[i]])
  species <- names(species)
  CC <- c("Ccycling")
  species_diff <- intersect(CC,species)
  ES_lost <- (length(CC)-length(species_diff))
  stats_CC11 <- rbind(stats_CC11, ES_lost)
}

stats_CC11$pri_ext <- 1:nrow(stats_CC11)
num <- count(stats_CC11)
num <- as.integer(num)
stats_CC11$n <- num - stats_CC11$pri_ext

stats_CC11 <- top_n(stats_CC11, 115, n)

#CS
stats_CS4 <- data.frame()
for (i in 1:length(net4_ES)){
  species <- as.data.frame(net4_ES[[i]])
  species <- names(species)
  CS <- c("Csequestration")
  species_diff <- intersect(CS,species)
  ES_lost <- (length(CS)-length(species_diff))
  stats_CS4 <- rbind(stats_CS4, ES_lost)
}

stats_CS4$pri_ext <- 1:nrow(stats_CS4)
num <- count(stats_CS4)
num <- as.integer(num)
stats_CS4$n <- num - stats_CS4$pri_ext

stats_CS4 <- top_n(stats_CS4, nrow(stats_spp4), n)

stats_CS5 <- data.frame()
for (i in 1:length(net5_ES)){
  species <- as.data.frame(net5_ES[[i]])
  species <- names(species)
  CS <- c("Csequestration")
  species_diff <- intersect(CS,species)
  ES_lost <- (length(CS)-length(species_diff))
  stats_CS5 <- rbind(stats_CS5, ES_lost)
}

stats_CS5$pri_ext <- 1:nrow(stats_CS5)
num <- count(stats_CS5)
num <- as.integer(num)
stats_CS5$n <- num - stats_CS5$pri_ext

stats_CS5 <- top_n(stats_CS5, nrow(stats_spp5), n)

stats_CS6 <- data.frame()
for (i in 1:length(net6_ES)){
  species <- as.data.frame(net6_ES[[i]])
  species <- names(species)
  CS <- c("Csequestration")
  species_diff <- intersect(CS,species)
  ES_lost <- (length(CS)-length(species_diff))
  stats_CS6 <- rbind(stats_CS6, ES_lost)
}

stats_CS6$pri_ext <- 1:nrow(stats_CS6)
num <- count(stats_CS6)
num <- as.integer(num)
stats_CS6$n <- num - stats_CS6$pri_ext

stats_CS6 <- top_n(stats_CS6, nrow(stats_spp6), n)

stats_CS7 <- data.frame()
for (i in 1:length(net7_ES)){
  species <- as.data.frame(net7_ES[[i]])
  species <- names(species)
  CS <- c("Csequestration")
  species_diff <- intersect(CS,species)
  ES_lost <- (length(CS)-length(species_diff))
  stats_CS7 <- rbind(stats_CS7, ES_lost)
}

stats_CS7$pri_ext <- 1:nrow(stats_CS7)
num <- count(stats_CS7)
num <- as.integer(num)
stats_CS7$n <- num - stats_CS7$pri_ext

stats_CS7 <- top_n(stats_CS7, nrow(stats_spp7), n)

stats_CS8 <- data.frame()
for (i in 1:length(net8_ES)){
  species <- as.data.frame(net8_ES[[i]])
  species <- names(species)
  CS <- c("Csequestration")
  species_diff <- intersect(CS,species)
  ES_lost <- (length(CS)-length(species_diff))
  stats_CS8 <- rbind(stats_CS8, ES_lost)
}

stats_CS8$pri_ext <- 1:nrow(stats_CS8)
num <- count(stats_CS8)
num <- as.integer(num)
stats_CS8$n <- num - stats_CS8$pri_ext

stats_CS8 <- top_n(stats_CS8, 82, n)

stats_CS9 <- data.frame()
for (i in 1:length(net9_ES)){
  species <- as.data.frame(net9_ES[[i]])
  species <- names(species)
  CS <- c("Csequestration")
  species_diff <- intersect(CS,species)
  ES_lost <- (length(CS)-length(species_diff))
  stats_CS9 <- rbind(stats_CS9, ES_lost)
}

stats_CS9$pri_ext <- 1:nrow(stats_CS9)
num <- count(stats_CS9)
num <- as.integer(num)
stats_CS9$n <- num - stats_CS9$pri_ext

stats_CS9 <- top_n(stats_CS9, 140, n)

stats_CS10 <- data.frame()
for (i in 1:length(net10_ES)){
  species <- as.data.frame(net10_ES[[i]])
  species <- names(species)
  CS <- c("Csequestration")
  species_diff <- intersect(CS,species)
  ES_lost <- (length(CS)-length(species_diff))
  stats_CS10 <- rbind(stats_CS10, ES_lost)
}

stats_CS10$pri_ext <- 1:nrow(stats_CS10)
num <- count(stats_CS10)
num <- as.integer(num)
stats_CS10$n <- num - stats_CS10$pri_ext

stats_CS10 <- top_n(stats_CS10, 156, n)

stats_CS11 <- data.frame()
for (i in 1:length(net11_ES)){
  species <- as.data.frame(net11_ES[[i]])
  species <- names(species)
  CS <- c("Csequestration")
  species_diff <- intersect(CS,species)
  ES_lost <- (length(CS)-length(species_diff))
  stats_CS11 <- rbind(stats_CS11, ES_lost)
}

stats_CS11$pri_ext <- 1:nrow(stats_CS11)
num <- count(stats_CS11)
num <- as.integer(num)
stats_CS11$n <- num - stats_CS11$pri_ext

stats_CS11 <- top_n(stats_CS11, 115, n)

#CV
stats_CV4 <- data.frame()
for (i in 1:length(net4_ES)){
  species <- as.data.frame(net4_ES[[i]])
  species <- names(species)
  CV <- c("LTCV")
  species_diff <- intersect(CV,species)
  ES_lost <- (length(CV)-length(species_diff))
  stats_CV4 <- rbind(stats_CV4, ES_lost)
}

stats_CV4$pri_ext <- 1:nrow(stats_CV4)
num <- count(stats_CV4)
num <- as.integer(num)
stats_CV4$n <- num - stats_CV4$pri_ext

stats_CV4 <- top_n(stats_CV4, nrow(stats_spp4), n)

stats_CV5 <- data.frame()
for (i in 1:length(net5_ES)){
  species <- as.data.frame(net5_ES[[i]])
  species <- names(species)
  CV <- c("LTCV")
  species_diff <- intersect(CV,species)
  ES_lost <- (length(CV)-length(species_diff))
  stats_CV5 <- rbind(stats_CV5, ES_lost)
}

stats_CV5$pri_ext <- 1:nrow(stats_CV5)
num <- count(stats_CV5)
num <- as.integer(num)
stats_CV5$n <- num - stats_CV5$pri_ext

stats_CV5 <- top_n(stats_CV5, nrow(stats_spp5), n)

stats_CV6 <- data.frame()
for (i in 1:length(net6_ES)){
  species <- as.data.frame(net6_ES[[i]])
  species <- names(species)
  CV <- c("LTCV")
  species_diff <- intersect(CV,species)
  ES_lost <- (length(CV)-length(species_diff))
  stats_CV6 <- rbind(stats_CV6, ES_lost)
}

stats_CV6$pri_ext <- 1:nrow(stats_CV6)
num <- count(stats_CV6)
num <- as.integer(num)
stats_CV6$n <- num - stats_CV6$pri_ext

stats_CV6 <- top_n(stats_CV6, nrow(stats_spp6), n)

stats_CV7 <- data.frame()
for (i in 1:length(net7_ES)){
  species <- as.data.frame(net7_ES[[i]])
  species <- names(species)
  CV <- c("LTCV")
  species_diff <- intersect(CV,species)
  ES_lost <- (length(CV)-length(species_diff))
  stats_CV7 <- rbind(stats_CV7, ES_lost)
}

stats_CV7$pri_ext <- 1:nrow(stats_CV7)
num <- count(stats_CV7)
num <- as.integer(num)
stats_CV7$n <- num - stats_CV7$pri_ext

stats_CV7 <- top_n(stats_CV7, nrow(stats_spp7), n)

stats_CV8 <- data.frame()
for (i in 1:length(net8_ES)){
  species <- as.data.frame(net8_ES[[i]])
  species <- names(species)
  CV <- c("LTCV")
  species_diff <- intersect(CV,species)
  ES_lost <- (length(CV)-length(species_diff))
  stats_CV8 <- rbind(stats_CV8, ES_lost)
}

stats_CV8$pri_ext <- 1:nrow(stats_CV8)
num <- count(stats_CV8)
num <- as.integer(num)
stats_CV8$n <- num - stats_CV8$pri_ext

stats_CV8 <- top_n(stats_CV8, 82, n)

stats_CV9 <- data.frame()
for (i in 1:length(net9_ES)){
  species <- as.data.frame(net9_ES[[i]])
  species <- names(species)
  CV <- c("LTCV")
  species_diff <- intersect(CV,species)
  ES_lost <- (length(CV)-length(species_diff))
  stats_CV9 <- rbind(stats_CV9, ES_lost)
}

stats_CV9$pri_ext <- 1:nrow(stats_CV9)
num <- count(stats_CV9)
num <- as.integer(num)
stats_CV9$n <- num - stats_CV9$pri_ext

stats_CV9 <- top_n(stats_CV9, 140, n)

stats_CV10 <- data.frame()
for (i in 1:length(net10_ES)){
  species <- as.data.frame(net10_ES[[i]])
  species <- names(species)
  CV <- c("LTCV")
  species_diff <- intersect(CV,species)
  ES_lost <- (length(CV)-length(species_diff))
  stats_CV10 <- rbind(stats_CV10, ES_lost)
}

stats_CV10$pri_ext <- 1:nrow(stats_CV10)
num <- count(stats_CV10)
num <- as.integer(num)
stats_CV10$n <- num - stats_CV10$pri_ext

stats_CV10 <- top_n(stats_CV10, 156, n)

stats_CV11 <- data.frame()
for (i in 1:length(net11_ES)){
  species <- as.data.frame(net11_ES[[i]])
  species <- names(species)
  CV <- c("LTCV")
  species_diff <- intersect(CV,species)
  ES_lost <- (length(CV)-length(species_diff))
  stats_CV11 <- rbind(stats_CV11, ES_lost)
}

stats_CV11$pri_ext <- 1:nrow(stats_CV11)
num <- count(stats_CV11)
num <- as.integer(num)
stats_CV11$n <- num - stats_CV11$pri_ext

stats_CV11 <- top_n(stats_CV11, 115, n)

#EE
stats_EE4 <- data.frame()
for (i in 1:length(net4_ES)){
  species <- as.data.frame(net4_ES[[i]])
  species <- names(species)
  EE <- c("Education")
  species_diff <- intersect(EE,species)
  ES_lost <- (length(EE)-length(species_diff))
  stats_EE4 <- rbind(stats_EE4, ES_lost)
}

stats_EE4$pri_ext <- 1:nrow(stats_EE4)
num <- count(stats_EE4)
num <- as.integer(num)
stats_EE4$n <- num - stats_EE4$pri_ext

stats_EE4 <- top_n(stats_EE4, nrow(stats_spp4), n)

stats_EE5 <- data.frame()
for (i in 1:length(net5_ES)){
  species <- as.data.frame(net5_ES[[i]])
  species <- names(species)
  EE <- c("Education")
  species_diff <- intersect(EE,species)
  ES_lost <- (length(EE)-length(species_diff))
  stats_EE5 <- rbind(stats_EE5, ES_lost)
}

stats_EE5$pri_ext <- 1:nrow(stats_EE5)
num <- count(stats_EE5)
num <- as.integer(num)
stats_EE5$n <- num - stats_EE5$pri_ext

stats_EE5 <- top_n(stats_EE5, nrow(stats_spp5), n)

stats_EE6 <- data.frame()
for (i in 1:length(net6_ES)){
  species <- as.data.frame(net6_ES[[i]])
  species <- names(species)
  EE <- c("Education")
  species_diff <- intersect(EE,species)
  ES_lost <- (length(EE)-length(species_diff))
  stats_EE6 <- rbind(stats_EE6, ES_lost)
}

stats_EE6$pri_ext <- 1:nrow(stats_EE6)
num <- count(stats_EE6)
num <- as.integer(num)
stats_EE6$n <- num - stats_EE6$pri_ext

stats_EE6 <- top_n(stats_EE6, nrow(stats_spp6), n)

stats_EE7 <- data.frame()
for (i in 1:length(net7_ES)){
  species <- as.data.frame(net7_ES[[i]])
  species <- names(species)
  EE <- c("Education")
  species_diff <- intersect(EE,species)
  ES_lost <- (length(EE)-length(species_diff))
  stats_EE7 <- rbind(stats_EE7, ES_lost)
}

stats_EE7$pri_ext <- 1:nrow(stats_EE7)
num <- count(stats_EE7)
num <- as.integer(num)
stats_EE7$n <- num - stats_EE7$pri_ext

stats_EE7 <- top_n(stats_EE7, nrow(stats_spp7), n)

stats_EE8 <- data.frame()
for (i in 1:length(net8_ES)){
  species <- as.data.frame(net8_ES[[i]])
  species <- names(species)
  EE <- c("Education")
  species_diff <- intersect(EE,species)
  ES_lost <- (length(EE)-length(species_diff))
  stats_EE8 <- rbind(stats_EE8, ES_lost)
}

stats_EE8$pri_ext <- 1:nrow(stats_EE8)
num <- count(stats_EE8)
num <- as.integer(num)
stats_EE8$n <- num - stats_EE8$pri_ext

stats_EE8 <- top_n(stats_EE8, 82, n)

stats_EE9 <- data.frame()
for (i in 1:length(net9_ES)){
  species <- as.data.frame(net9_ES[[i]])
  species <- names(species)
  EE <- c("Education")
  species_diff <- intersect(EE,species)
  ES_lost <- (length(EE)-length(species_diff))
  stats_EE9 <- rbind(stats_EE9, ES_lost)
}

stats_EE9$pri_ext <- 1:nrow(stats_EE9)
num <- count(stats_EE9)
num <- as.integer(num)
stats_EE9$n <- num - stats_EE9$pri_ext

stats_EE9 <- top_n(stats_EE9, 140, n)

stats_EE10 <- data.frame()
for (i in 1:length(net10_ES)){
  species <- as.data.frame(net10_ES[[i]])
  species <- names(species)
  EE <- c("Education")
  species_diff <- intersect(EE,species)
  ES_lost <- (length(EE)-length(species_diff))
  stats_EE10 <- rbind(stats_EE10, ES_lost)
}

stats_EE10$pri_ext <- 1:nrow(stats_EE10)
num <- count(stats_EE10)
num <- as.integer(num)
stats_EE10$n <- num - stats_EE10$pri_ext

stats_EE10 <- top_n(stats_EE10, 156, n)

stats_EE11 <- data.frame()
for (i in 1:length(net11_ES)){
  species <- as.data.frame(net11_ES[[i]])
  species <- names(species)
  EE <- c("Education")
  species_diff <- intersect(EE,species)
  ES_lost <- (length(EE)-length(species_diff))
  stats_EE11 <- rbind(stats_EE11, ES_lost)
}

stats_EE11$pri_ext <- 1:nrow(stats_EE11)
num <- count(stats_EE11)
num <- as.integer(num)
stats_EE11$n <- num - stats_EE11$pri_ext

stats_EE11 <- top_n(stats_EE11, 115, n)

```

```{r}
#rb calculation
providers <- subset(links, links$edgetype == 1)
providers <- as.vector(providers[,1])
providers <- unique(providers)

ES <- subset(nodes, nodes$vertextype > 2)
ES <- as.vector(ES[,1])
all <- as.vector(SPPnodes[,1])
ESall <- length(all) + length(ES)
susc <- length(all)-basal

#FI
stats_FI4$prop_surv <- (1-stats_FI4$X0L)
stats_FI4$prop_ext <- stats_FI4$pri_ext/ESall
stats_FI4 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_FI4)+1, prop_surv = 1, prop_ext = 0), stats_FI4)
AUC_FI4 <- AUC(stats_FI4$prop_ext, stats_FI4$prop_surv, from = min(min(stats_FI4$prop_ext)), to = max(max(stats_FI4$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_FI5$prop_surv <- (1-stats_FI5$X0L)
stats_FI5$prop_ext <- stats_FI5$pri_ext/ESall
stats_FI5 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_FI5)+1, prop_surv = 1, prop_ext = 0), stats_FI5)
AUC_FI5 <- AUC(stats_FI5$prop_ext, stats_FI5$prop_surv, from = min(min(stats_FI5$prop_ext)), to = max(max(stats_FI5$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_FI6$prop_surv <- (1-stats_FI6$X0L)
stats_FI6$prop_ext <- stats_FI6$pri_ext/ESall
stats_FI6 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_FI6)+1, prop_surv = 1, prop_ext = 0), stats_FI6)
AUC_FI6 <- AUC(stats_FI6$prop_ext, stats_FI6$prop_surv, from = min(min(stats_FI6$prop_ext)), to = max(max(stats_FI6$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_FI7$prop_surv <- (1-stats_FI7$X0L)
stats_FI7$prop_ext <- stats_FI7$pri_ext/ESall
stats_FI7 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_FI7)+1, prop_surv = 1, prop_ext = 0), stats_FI7)
AUC_FI7 <- AUC(stats_FI7$prop_ext, stats_FI7$prop_surv, from = min(min(stats_FI7$prop_ext)), to = max(max(stats_FI7$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_FI8$prop_surv <- (1-stats_FI8$X0L)
stats_FI8$prop_ext <- stats_FI8$pri_ext/length(providers)
stats_FI8 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_FI8)+1, prop_surv = 1, prop_ext = 0), stats_FI8)
AUC_FI8 <- AUC(stats_FI8$prop_ext, stats_FI8$prop_surv, from = min(min(stats_FI8$prop_ext)), to = max(max(stats_FI8$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_FI9$prop_surv <- (1-stats_FI9$X0L)
stats_FI9$prop_ext <- stats_FI9$pri_ext/length(supporters)
stats_FI9 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_FI9)+1, prop_surv = 1, prop_ext = 0), stats_FI9)
AUC_FI9 <- AUC(stats_FI9$prop_ext, stats_FI9$prop_surv, from = min(min(stats_FI9$prop_ext)), to = max(max(stats_FI9$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_FI10$prop_surv <- (1-stats_FI10$X0L)
stats_FI10$prop_ext <- stats_FI10$pri_ext/length(supporters)
stats_FI10 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_FI10)+1, prop_surv = 1, prop_ext = 0), stats_FI10)
AUC_FI10 <- AUC(stats_FI10$prop_ext, stats_FI10$prop_surv, from = min(min(stats_FI10$prop_ext)), to = max(max(stats_FI10$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_FI11$prop_surv <- (1-stats_FI11$X0L)
stats_FI11$prop_ext <- stats_FI11$pri_ext/length(supporters)
stats_FI11 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_FI11)+1, prop_surv = 1, prop_ext = 0), stats_FI11)
AUC_FI11 <- AUC(stats_FI11$prop_ext, stats_FI11$prop_surv, from = min(min(stats_FI11$prop_ext)), to = max(max(stats_FI11$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

#RM
stats_RM4$prop_surv <- (1-stats_RM4$X0L)
stats_RM4$prop_ext <- stats_RM4$pri_ext/ESall
stats_RM4 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_RM4)+1, prop_surv = 1, prop_ext = 0), stats_RM4)
AUC_RM4 <- AUC(stats_RM4$prop_ext, stats_RM4$prop_surv, from = min(min(stats_RM4$prop_ext)), to = max(max(stats_RM4$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_RM5$prop_surv <- (1-stats_RM5$X0L)
stats_RM5$prop_ext <- stats_RM5$pri_ext/ESall
stats_RM5 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_RM5)+1, prop_surv = 1, prop_ext = 0), stats_RM5)
AUC_RM5 <- AUC(stats_RM5$prop_ext, stats_RM5$prop_surv, from = min(min(stats_RM5$prop_ext)), to = max(max(stats_RM5$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_RM6$prop_surv <- (1-stats_RM6$X0L)
stats_RM6$prop_ext <- stats_RM6$pri_ext/ESall
stats_RM6 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_RM6)+1, prop_surv = 1, prop_ext = 0), stats_RM6)
AUC_RM6 <- AUC(stats_RM6$prop_ext, stats_RM6$prop_surv, from = min(min(stats_RM6$prop_ext)), to = max(max(stats_RM6$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_RM7$prop_surv <- (1-stats_RM7$X0L)
stats_RM7$prop_ext <- stats_RM7$pri_ext/ESall
stats_RM7 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_RM7)+1, prop_surv = 1, prop_ext = 0), stats_RM7)
AUC_RM7 <- AUC(stats_RM7$prop_ext, stats_RM7$prop_surv, from = min(min(stats_RM7$prop_ext)), to = max(max(stats_RM7$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_RM8$prop_surv <- (1-stats_RM8$X0L)
stats_RM8$prop_ext <- stats_RM8$pri_ext/length(providers)
stats_RM8 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_RM8)+1, prop_surv = 1, prop_ext = 0), stats_RM8)
AUC_RM8 <- AUC(stats_RM8$prop_ext, stats_RM8$prop_surv, from = min(min(stats_RM8$prop_ext)), to = max(max(stats_RM8$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_RM9$prop_surv <- (1-stats_RM9$X0L)
stats_RM9$prop_ext <- stats_RM9$pri_ext/length(supporters)
stats_RM9 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_RM9)+1, prop_surv = 1, prop_ext = 0), stats_RM9)
AUC_RM9 <- AUC(stats_RM9$prop_ext, stats_RM9$prop_surv, from = min(min(stats_RM9$prop_ext)), to = max(max(stats_RM9$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_RM10$prop_surv <- (1-stats_RM10$X0L)
stats_RM10$prop_ext <- stats_RM10$pri_ext/length(supporters)
stats_RM10 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_RM10)+1, prop_surv = 1, prop_ext = 0), stats_RM10)
AUC_RM10 <- AUC(stats_RM10$prop_ext, stats_RM10$prop_surv, from = min(min(stats_RM10$prop_ext)), to = max(max(stats_RM10$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_RM11$prop_surv <- (1-stats_RM11$X0L)
stats_RM11$prop_ext <- stats_RM11$pri_ext/length(supporters)
stats_RM11 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_RM11)+1, prop_surv = 1, prop_ext = 0), stats_RM11)
AUC_RM11 <- AUC(stats_RM11$prop_ext, stats_RM11$prop_surv, from = min(min(stats_RM11$prop_ext)), to = max(max(stats_RM11$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

#HF
stats_HF4$prop_surv <- (1-stats_HF4$X0L)
stats_HF4$prop_ext <- stats_HF4$pri_ext/ESall
stats_HF4 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_HF4)+1, prop_surv = 1, prop_ext = 0), stats_HF4)
AUC_HF4 <- AUC(stats_HF4$prop_ext, stats_HF4$prop_surv, from = min(min(stats_HF4$prop_ext)), to = max(max(stats_HF4$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_HF5$prop_surv <- (1-stats_HF5$X0L)
stats_HF5$prop_ext <- stats_HF5$pri_ext/ESall
stats_HF5 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_HF5)+1, prop_surv = 1, prop_ext = 0), stats_HF5)
AUC_HF5 <- AUC(stats_HF5$prop_ext, stats_HF5$prop_surv, from = min(min(stats_HF5$prop_ext)), to = max(max(stats_HF5$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_HF6$prop_surv <- (1-stats_HF6$X0L)
stats_HF6$prop_ext <- stats_HF6$pri_ext/ESall
stats_HF6 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_HF6)+1, prop_surv = 1, prop_ext = 0), stats_HF6)
AUC_HF6 <- AUC(stats_HF6$prop_ext, stats_HF6$prop_surv, from = min(min(stats_HF6$prop_ext)), to = max(max(stats_HF6$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_HF7$prop_surv <- (1-stats_HF7$X0L)
stats_HF7$prop_ext <- stats_HF7$pri_ext/ESall
stats_HF7 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_HF7)+1, prop_surv = 1, prop_ext = 0), stats_HF7)
AUC_HF7 <- AUC(stats_HF7$prop_ext, stats_HF7$prop_surv, from = min(min(stats_HF7$prop_ext)), to = max(max(stats_HF7$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_HF8$prop_surv <- (1-stats_HF8$X0L)
stats_HF8$prop_ext <- stats_HF8$pri_ext/length(providers)
stats_HF8 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_HF8)+1, prop_surv = 1, prop_ext = 0), stats_HF8)
AUC_HF8 <- AUC(stats_HF8$prop_ext, stats_HF8$prop_surv, from = min(min(stats_HF8$prop_ext)), to = max(max(stats_HF8$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_HF9$prop_surv <- (1-stats_HF9$X0L)
stats_HF9$prop_ext <- stats_HF9$pri_ext/length(supporters)
stats_HF9 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_HF9)+1, prop_surv = 1, prop_ext = 0), stats_HF9)
AUC_HF9 <- AUC(stats_HF9$prop_ext, stats_HF9$prop_surv, from = min(min(stats_HF9$prop_ext)), to = max(max(stats_HF9$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_HF10$prop_surv <- (1-stats_HF10$X0L)
stats_HF10$prop_ext <- stats_HF10$pri_ext/length(supporters)
stats_HF10 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_HF10)+1, prop_surv = 1, prop_ext = 0), stats_HF10)
AUC_HF10 <- AUC(stats_HF10$prop_ext, stats_HF10$prop_surv, from = min(min(stats_HF10$prop_ext)), to = max(max(stats_HF10$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_HF11$prop_surv <- (1-stats_HF11$X0L)
stats_HF11$prop_ext <- stats_HF11$pri_ext/length(supporters)
stats_HF11 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_HF11)+1, prop_surv = 1, prop_ext = 0), stats_HF11)
AUC_HF11 <- AUC(stats_HF11$prop_ext, stats_HF11$prop_surv, from = min(min(stats_HF11$prop_ext)), to = max(max(stats_HF11$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

#BP
stats_BP4$prop_surv <- (1-stats_BP4$X0L)
stats_BP4$prop_ext <- stats_BP4$pri_ext/ESall
stats_BP4 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_BP4)+1, prop_surv = 1, prop_ext = 0), stats_BP4)
AUC_BP4 <- AUC(stats_BP4$prop_ext, stats_BP4$prop_surv, from = min(min(stats_BP4$prop_ext)), to = max(max(stats_BP4$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_BP5$prop_surv <- (1-stats_BP5$X0L)
stats_BP5$prop_ext <- stats_BP5$pri_ext/ESall
stats_BP5 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_BP5)+1, prop_surv = 1, prop_ext = 0), stats_BP5)
AUC_BP5 <- AUC(stats_BP5$prop_ext, stats_BP5$prop_surv, from = min(min(stats_BP5$prop_ext)), to = max(max(stats_BP5$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_BP6$prop_surv <- (1-stats_BP6$X0L)
stats_BP6$prop_ext <- stats_BP6$pri_ext/ESall
stats_BP6 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_BP6)+1, prop_surv = 1, prop_ext = 0), stats_BP6)
AUC_BP6 <- AUC(stats_BP6$prop_ext, stats_BP6$prop_surv, from = min(min(stats_BP6$prop_ext)), to = max(max(stats_BP6$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_BP7$prop_surv <- (1-stats_BP7$X0L)
stats_BP7$prop_ext <- stats_BP7$pri_ext/ESall
stats_BP7 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_BP7)+1, prop_surv = 1, prop_ext = 0), stats_BP7)
AUC_BP7 <- AUC(stats_BP7$prop_ext, stats_BP7$prop_surv, from = min(min(stats_BP7$prop_ext)), to = max(max(stats_BP7$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_BP8$prop_surv <- (1-stats_BP8$X0L)
stats_BP8$prop_ext <- stats_BP8$pri_ext/length(providers)
stats_BP8 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_BP8)+1, prop_surv = 1, prop_ext = 0), stats_BP8)
AUC_BP8 <- AUC(stats_BP8$prop_ext, stats_BP8$prop_surv, from = min(min(stats_BP8$prop_ext)), to = max(max(stats_BP8$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_BP9$prop_surv <- (1-stats_BP9$X0L)
stats_BP9$prop_ext <- stats_BP9$pri_ext/length(supporters)
stats_BP9 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_BP9)+1, prop_surv = 1, prop_ext = 0), stats_BP9)
AUC_BP9 <- AUC(stats_BP9$prop_ext, stats_BP9$prop_surv, from = min(min(stats_BP9$prop_ext)), to = max(max(stats_BP9$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_BP10$prop_surv <- (1-stats_BP10$X0L)
stats_BP10$prop_ext <- stats_BP10$pri_ext/length(supporters)
stats_BP10 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_BP10)+1, prop_surv = 1, prop_ext = 0), stats_BP10)
AUC_BP10 <- AUC(stats_BP10$prop_ext, stats_BP10$prop_surv, from = min(min(stats_BP10$prop_ext)), to = max(max(stats_BP10$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_BP11$prop_surv <- (1-stats_BP11$X0L)
stats_BP11$prop_ext <- stats_BP11$pri_ext/length(supporters)
stats_BP11 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_BP11)+1, prop_surv = 1, prop_ext = 0), stats_BP11)
AUC_BP11 <- AUC(stats_BP11$prop_ext, stats_BP11$prop_surv, from = min(min(stats_BP11$prop_ext)), to = max(max(stats_BP11$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

#CC
stats_CC4$prop_surv <- (1-stats_CC4$X0L)
stats_CC4$prop_ext <- stats_CC4$pri_ext/ESall
stats_CC4 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CC4)+1, prop_surv = 1, prop_ext = 0), stats_CC4)
AUC_CC4 <- AUC(stats_CC4$prop_ext, stats_CC4$prop_surv, from = min(min(stats_CC4$prop_ext)), to = max(max(stats_CC4$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CC5$prop_surv <- (1-stats_CC5$X0L)
stats_CC5$prop_ext <- stats_CC5$pri_ext/ESall
stats_CC5 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CC5)+1, prop_surv = 1, prop_ext = 0), stats_CC5)
AUC_CC5 <- AUC(stats_CC5$prop_ext, stats_CC5$prop_surv, from = min(min(stats_CC5$prop_ext)), to = max(max(stats_CC5$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CC6$prop_surv <- (1-stats_CC6$X0L)
stats_CC6$prop_ext <- stats_CC6$pri_ext/ESall
stats_CC6 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CC6)+1, prop_surv = 1, prop_ext = 0), stats_CC6)
AUC_CC6 <- AUC(stats_CC6$prop_ext, stats_CC6$prop_surv, from = min(min(stats_CC6$prop_ext)), to = max(max(stats_CC6$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CC7$prop_surv <- (1-stats_CC7$X0L)
stats_CC7$prop_ext <- stats_CC7$pri_ext/ESall
stats_CC7 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CC7)+1, prop_surv = 1, prop_ext = 0), stats_CC7)
AUC_CC7 <- AUC(stats_CC7$prop_ext, stats_CC7$prop_surv, from = min(min(stats_CC7$prop_ext)), to = max(max(stats_CC7$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CC8$prop_surv <- (1-stats_CC8$X0L)
stats_CC8$prop_ext <- stats_CC8$pri_ext/length(providers)
stats_CC8 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CC8)+1, prop_surv = 1, prop_ext = 0), stats_CC8)
AUC_CC8 <- AUC(stats_CC8$prop_ext, stats_CC8$prop_surv, from = min(min(stats_CC8$prop_ext)), to = max(max(stats_CC8$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CC9$prop_surv <- (1-stats_CC9$X0L)
stats_CC9$prop_ext <- stats_CC9$pri_ext/length(supporters)
stats_CC9 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CC9)+1, prop_surv = 1, prop_ext = 0), stats_CC9)
AUC_CC9 <- AUC(stats_CC9$prop_ext, stats_CC9$prop_surv, from = min(min(stats_CC9$prop_ext)), to = max(max(stats_CC9$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CC10$prop_surv <- (1-stats_CC10$X0L)
stats_CC10$prop_ext <- stats_CC10$pri_ext/length(supporters)
stats_CC10 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CC10)+1, prop_surv = 1, prop_ext = 0), stats_CC10)
AUC_CC10 <- AUC(stats_CC10$prop_ext, stats_CC10$prop_surv, from = min(min(stats_CC10$prop_ext)), to = max(max(stats_CC10$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CC11$prop_surv <- (1-stats_CC11$X0L)
stats_CC11$prop_ext <- stats_CC11$pri_ext/length(supporters)
stats_CC11 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CC11)+1, prop_surv = 1, prop_ext = 0), stats_CC11)
AUC_CC11 <- AUC(stats_CC11$prop_ext, stats_CC11$prop_surv, from = min(min(stats_CC11$prop_ext)), to = max(max(stats_CC11$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

#CS
stats_CS4$prop_surv <- (1-stats_CS4$X0L)
stats_CS4$prop_ext <- stats_CS4$pri_ext/ESall
stats_CS4 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CS4)+1, prop_surv = 1, prop_ext = 0), stats_CS4)
AUC_CS4 <- AUC(stats_CS4$prop_ext, stats_CS4$prop_surv, from = min(min(stats_CS4$prop_ext)), to = max(max(stats_CS4$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CS5$prop_surv <- (1-stats_CS5$X0L)
stats_CS5$prop_ext <- stats_CS5$pri_ext/ESall
stats_CS5 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CS5)+1, prop_surv = 1, prop_ext = 0), stats_CS5)
AUC_CS5 <- AUC(stats_CS5$prop_ext, stats_CS5$prop_surv, from = min(min(stats_CS5$prop_ext)), to = max(max(stats_CS5$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CS6$prop_surv <- (1-stats_CS6$X0L)
stats_CS6$prop_ext <- stats_CS6$pri_ext/ESall
stats_CS6 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CS6)+1, prop_surv = 1, prop_ext = 0), stats_CS6)
AUC_CS6 <- AUC(stats_CS6$prop_ext, stats_CS6$prop_surv, from = min(min(stats_CS6$prop_ext)), to = max(max(stats_CS6$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CS7$prop_surv <- (1-stats_CS7$X0L)
stats_CS7$prop_ext <- stats_CS7$pri_ext/ESall
stats_CS7 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CS7)+1, prop_surv = 1, prop_ext = 0), stats_CS7)
AUC_CS7 <- AUC(stats_CS7$prop_ext, stats_CS7$prop_surv, from = min(min(stats_CS7$prop_ext)), to = max(max(stats_CS7$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CS8$prop_surv <- (1-stats_CS8$X0L)
stats_CS8$prop_ext <- stats_CS8$pri_ext/length(providers)
stats_CS8 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CS8)+1, prop_surv = 1, prop_ext = 0), stats_CS8)
AUC_CS8 <- AUC(stats_CS8$prop_ext, stats_CS8$prop_surv, from = min(min(stats_CS8$prop_ext)), to = max(max(stats_CS8$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CS9$prop_surv <- (1-stats_CS9$X0L)
stats_CS9$prop_ext <- stats_CS9$pri_ext/length(supporters)
stats_CS9 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CS9)+1, prop_surv = 1, prop_ext = 0), stats_CS9)
AUC_CS9 <- AUC(stats_CS9$prop_ext, stats_CS9$prop_surv, from = min(min(stats_CS9$prop_ext)), to = max(max(stats_CS9$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CS10$prop_surv <- (1-stats_CS10$X0L)
stats_CS10$prop_ext <- stats_CS10$pri_ext/length(supporters)
stats_CS10 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CS10)+1, prop_surv = 1, prop_ext = 0), stats_CS10)
AUC_CS10 <- AUC(stats_CS10$prop_ext, stats_CS10$prop_surv, from = min(min(stats_CS10$prop_ext)), to = max(max(stats_CS10$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CS11$prop_surv <- (1-stats_CS11$X0L)
stats_CS11$prop_ext <- stats_CS11$pri_ext/length(supporters)
stats_CS11 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CS11)+1, prop_surv = 1, prop_ext = 0), stats_CS11)
AUC_CS11 <- AUC(stats_CS11$prop_ext, stats_CS11$prop_surv, from = min(min(stats_CS11$prop_ext)), to = max(max(stats_CS11$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

#cv
stats_CV4$prop_surv <- (1-stats_CV4$X0L)
stats_CV4$prop_ext <- stats_CV4$pri_ext/ESall
stats_CV4 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CV4)+1, prop_surv = 1, prop_ext = 0), stats_CV4)
AUC_CV4 <- AUC(stats_CV4$prop_ext, stats_CV4$prop_surv, from = min(min(stats_CV4$prop_ext)), to = max(max(stats_CV4$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CV5$prop_surv <- (1-stats_CV5$X0L)
stats_CV5$prop_ext <- stats_CV5$pri_ext/ESall
stats_CV5 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CV5)+1, prop_surv = 1, prop_ext = 0), stats_CV5)
AUC_CV5 <- AUC(stats_CV5$prop_ext, stats_CV5$prop_surv, from = min(min(stats_CV5$prop_ext)), to = max(max(stats_CV5$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CV6$prop_surv <- (1-stats_CV6$X0L)
stats_CV6$prop_ext <- stats_CV6$pri_ext/ESall
stats_CV6 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CV6)+1, prop_surv = 1, prop_ext = 0), stats_CV6)
AUC_CV6 <- AUC(stats_CV6$prop_ext, stats_CV6$prop_surv, from = min(min(stats_CV6$prop_ext)), to = max(max(stats_CV6$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CV7$prop_surv <- (1-stats_CV7$X0L)
stats_CV7$prop_ext <- stats_CV7$pri_ext/ESall
stats_CV7 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CV7)+1, prop_surv = 1, prop_ext = 0), stats_CV7)
AUC_CV7 <- AUC(stats_CV7$prop_ext, stats_CV7$prop_surv, from = min(min(stats_CV7$prop_ext)), to = max(max(stats_CV7$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CV8$prop_surv <- (1-stats_CV8$X0L)
stats_CV8$prop_ext <- stats_CV8$pri_ext/length(providers)
statsCV8 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CV8)+1, prop_surv = 1, prop_ext = 0), stats_CV8)
AUC_CV8 <- AUC(stats_CV8$prop_ext, stats_CV8$prop_surv, from = min(min(stats_CV8$prop_ext)), to = max(max(stats_CV8$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CV9$prop_surv <- (1-stats_CV9$X0L)
stats_CV9$prop_ext <- stats_CV9$pri_ext/length(supporters)
stats_CV9 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CV9)+1, prop_surv = 1, prop_ext = 0), stats_CV9)
AUC_CV9 <- AUC(stats_CV9$prop_ext, stats_CV9$prop_surv, from = min(min(stats_CV9$prop_ext)), to = max(max(stats_CV9$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CV10$prop_surv <- (1-stats_CV10$X0L)
stats_CV10$prop_ext <- stats_CV10$pri_ext/length(supporters)
stats_CV10 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CV10)+1, prop_surv = 1, prop_ext = 0), stats_CV10)
AUC_CV10 <- AUC(stats_CV10$prop_ext, stats_CV10$prop_surv, from = min(min(stats_CV10$prop_ext)), to = max(max(stats_CV10$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_CV11$prop_surv <- (1-stats_CV11$X0L)
stats_CV11$prop_ext <- stats_CV11$pri_ext/length(supporters)
stats_CV11 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_CV11)+1, prop_surv = 1, prop_ext = 0), stats_CV11)
AUC_CV11 <- AUC(stats_CV11$prop_ext, stats_CV11$prop_surv, from = min(min(stats_CV11$prop_ext)), to = max(max(stats_CV11$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

#para EE
stats_EE4$prop_surv <- (1-stats_EE4$X0L)
stats_EE4$prop_ext <- stats_EE4$pri_ext/ESall
stats_EE4 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_EE4)+1, prop_surv = 1, prop_ext = 0), stats_EE4)
AUC_EE4 <- AUC(stats_EE4$prop_ext, stats_EE4$prop_surv, from = min(min(stats_EE4$prop_ext)), to = max(max(stats_EE4$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_EE5$prop_surv <- (1-stats_EE5$X0L)
stats_EE5$prop_ext <- stats_EE5$pri_ext/ESall
stats_EE5 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_EE5)+1, prop_surv = 1, prop_ext = 0), stats_EE5)
AUC_EE5 <- AUC(stats_EE5$prop_ext, stats_EE5$prop_surv, from = min(min(stats_EE5$prop_ext)), to = max(max(stats_EE5$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_EE6$prop_surv <- (1-stats_EE6$X0L)
stats_EE6$prop_ext <- stats_EE6$pri_ext/ESall
stats_EE6 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_EE6)+1, prop_surv = 1, prop_ext = 0), stats_EE6)
AUC_EE6 <- AUC(stats_EE6$prop_ext, stats_EE6$prop_surv, from = min(min(stats_EE6$prop_ext)), to = max(max(stats_EE6$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_EE7$prop_surv <- (1-stats_EE7$X0L)
stats_EE7$prop_ext <- stats_EE7$pri_ext/ESall
stats_EE7 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_EE7)+1, prop_surv = 1, prop_ext = 0), stats_EE7)
AUC_EE7 <- AUC(stats_EE7$prop_ext, stats_EE7$prop_surv, from = min(min(stats_EE7$prop_ext)), to = max(max(stats_EE7$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_EE8$prop_surv <- (1-stats_EE8$X0L)
stats_EE8$prop_ext <- stats_EE8$pri_ext/length(providers)
stats_EE8 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_EE8)+1, prop_surv = 1, prop_ext = 0), stats_EE8)
AUC_EE8 <- AUC(stats_EE8$prop_ext, stats_EE8$prop_surv, from = min(min(stats_EE8$prop_ext)), to = max(max(stats_EE8$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_EE9$prop_surv <- (1-stats_EE9$X0L)
stats_EE9$prop_ext <- stats_EE9$pri_ext/length(supporters)
stats_EE9 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_EE9)+1, prop_surv = 1, prop_ext = 0), stats_EE9)
AUC_EE9 <- AUC(stats_EE9$prop_ext, stats_EE9$prop_surv, from = min(min(stats_EE9$prop_ext)), to = max(max(stats_EE9$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_EE10$prop_surv <- (1-stats_EE10$X0L)
stats_EE10$prop_ext <- stats_EE10$pri_ext/length(supporters)
stats_EE10 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_EE10)+1, prop_surv = 1, prop_ext = 0), stats_EE10)
AUC_EE10 <- AUC(stats_EE10$prop_ext, stats_EE10$prop_surv, from = min(min(stats_EE10$prop_ext)), to = max(max(stats_EE10$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

stats_EE11$prop_surv <- (1-stats_EE11$X0L)
stats_EE11$prop_ext <- stats_EE11$pri_ext/length(supporters)
stats_EE11 <- rbind(data.frame(X0L = 0, pri_ext = 0, n = nrow(stats_EE11)+1, prop_surv = 1, prop_ext = 0), stats_EE11)
AUC_EE11 <- AUC(stats_EE11$prop_ext, stats_EE11$prop_surv, from = min(min(stats_EE11$prop_ext)), to = max(max(stats_EE11$prop_ext)), method = c("trapezoid"), absolutearea = FALSE)

```

```{r}
#mean robustness calculation for each ES
rbmean_FI <- sum(AUC_FI4, AUC_FI5, AUC_FI6, AUC_FI7, AUC_FI8, AUC_FI9, AUC_FI10, AUC_FI11)/8
rbmean_RM <- sum(AUC_RM4, AUC_RM5, AUC_RM6, AUC_RM7, AUC_RM8, AUC_RM9, AUC_RM10, AUC_RM11)/8
rbmean_HF <- sum(AUC_HF4, AUC_HF5, AUC_HF6, AUC_HF7, AUC_HF8, AUC_HF9, AUC_HF10, AUC_HF11)/8
rbmean_BP <- sum(AUC_BP4, AUC_BP5, AUC_BP6, AUC_BP7, AUC_BP8, AUC_BP9, AUC_BP10, AUC_BP11)/8
rbmean_CC <- sum(AUC_CC4, AUC_CC5, AUC_CC6, AUC_CC7, AUC_CC8, AUC_CC9, AUC_CC10, AUC_CC11)/8
rbmean_CS <- sum(AUC_CS4, AUC_CS5, AUC_CS6, AUC_CS7, AUC_CS8, AUC_CS9, AUC_CS10, AUC_CS11)/8
rbmean_CV <- sum(AUC_CV4, AUC_CV5, AUC_CV6, AUC_CV7, AUC_CV8, AUC_CV9, AUC_CV10, AUC_CV11)/8
rbmean_EE <- sum(AUC_EE4, AUC_EE5, AUC_EE6, AUC_EE7, AUC_EE8, AUC_EE9, AUC_EE10, AUC_EE11)/8
rbmean <- c(rbmean_FI, rbmean_RM, rbmean_HF, rbmean_BP, rbmean_CC, rbmean_CS, rbmean_CV, rbmean_EE)

#aggregation of all robustness values
rbmean <- as.numeric(rbmean)
rb4 <- c(AUC_FI4, AUC_RM4, AUC_HF4, AUC_BP4, AUC_CC4, AUC_CS4, AUC_CV4, AUC_EE4)
rb5 <- c(AUC_FI5, AUC_RM5, AUC_HF5, AUC_BP5, AUC_CC5, AUC_CS5, AUC_CV5, AUC_EE5)
rb6 <- c(AUC_FI6, AUC_RM6, AUC_HF6, AUC_BP6, AUC_CC6, AUC_CS6, AUC_CV6, AUC_EE6)
rb7 <- c(AUC_FI7, AUC_RM7, AUC_HF7, AUC_BP7, AUC_CC7, AUC_CS7, AUC_CV7, AUC_EE7)
rb8 <- c(AUC_FI8, AUC_RM8, AUC_HF8, AUC_BP8, AUC_CC8, AUC_CS8, AUC_CV8, AUC_EE8)
rb9 <- c(AUC_FI9, AUC_RM9, AUC_HF9, AUC_BP9, AUC_CC9, AUC_CS9, AUC_CV9, AUC_EE9)
rb10 <- c(AUC_FI10, AUC_RM10, AUC_HF10, AUC_BP10, AUC_CC10, AUC_CS10, AUC_CV10, AUC_EE10)
rb11 <- c(AUC_FI11, AUC_RM11, AUC_HF11, AUC_BP11, AUC_CC11, AUC_CS11, AUC_CV11, AUC_EE11)
rb4 <- as.numeric(rb4)
rb5 <- as.numeric(rb5)
rb6 <- as.numeric(rb6)
rb7 <- as.numeric(rb7)
rb8 <- as.numeric(rb8)
rb9 <- as.numeric(rb9)
rb10 <- as.numeric(rb10)
rb11 <- as.numeric(rb11)

#topological stats calculations for all ES
ES <- c("FI", "RM", "HF", "BP", "CC", "CS", "CV", "EE")
ESnet <- graph.data.frame(links, directed = T, vertices = nodes)
ESmat <- as_adjacency_matrix(ESnet, sparse = FALSE, attr = NULL)
degree <- degree(ESnet)
nodes$degree <- degree
tl <- TrophInd(Tij = t(ESmat))
nodes$tl <- tl$TL
top <- calc_topological_roles(ESnet)
top <- top[match(c(386, 385, 380, 381, 382, 387, 384, 383), top$node), ]
am <- top$among_module_conn
wm <- top$within_module_degree

#dataframe creation
robustness <- subset(nodes, nodes$vertextype > 2)
robustness <- robustness[,c(1,3,4)]
robustness <- cbind(robustness, am, wm, rbmean, rb4, rb5, rb6, rb7, rb8, rb9, rb10, rb11)

#correlation calculations
#avg robustness
cor.test(robustness$rbmean, robustness$degree, method = "spearman")
summary(lm(robustness$rbmean ~ robustness$degree))
cor.test(robustness$rbmean, robustness$tl, method = "spearman")
cor.test(robustness$rbmean, robustness$wm, method = "spearman")
cor.test(robustness$rbmean, robustness$am, method = "spearman")

#seq 4
cor.test(robustness$rb4, robustness$degree, method = "spearman")
cor.test(robustness$rb4, robustness$tl, method = "spearman")
cor.test(robustness$rb4, robustness$am, method = "spearman")
cor.test(robustness$rb4, robustness$wm, method = "spearman")

#seq 5
cor.test(robustness$rb5, robustness$degree, method = "spearman")
cor.test(robustness$rb5, robustness$tl, method = "spearman")
cor.test(robustness$rb5, robustness$am, method = "spearman")
cor.test(robustness$rb5, robustness$wm, method = "spearman")

#seq 6
cor.test(robustness$rb6, robustness$degree, method = "spearman")
cor.test(robustness$rb6, robustness$tl, method = "spearman")
cor.test(robustness$rb6, robustness$am, method = "spearman")
cor.test(robustness$rb6, robustness$wm, method = "spearman")

#seq 7
cor.test(robustness$rb7, robustness$degree, method = "spearman")
cor.test(robustness$rb7, robustness$tl, method = "spearman")
cor.test(robustness$rb7, robustness$am, method = "spearman")
cor.test(robustness$rb7, robustness$wm, method = "spearman")

#seq 8
cor.test(robustness$rb8, robustness$degree, method = "spearman")
cor.test(robustness$rb8, robustness$tl, method = "spearman")
cor.test(robustness$rb8, robustness$am, method = "spearman")
cor.test(robustness$rb8, robustness$wm, method = "spearman")

#seq 9
cor.test(robustness$rb9, robustness$degree, method = "spearman")
cor.test(robustness$rb9, robustness$tl, method = "spearman")
cor.test(robustness$rb9, robustness$am, method = "spearman")
cor.test(robustness$rb9, robustness$wm, method = "spearman")

#seq 10
cor.test(robustness$rb10, robustness$degree, method = "spearman")
cor.test(robustness$rb10, robustness$tl, method = "spearman")
cor.test(robustness$rb10, robustness$am, method = "spearman")
cor.test(robustness$rb10, robustness$wm, method = "spearman")

#seq 11
cor.test(robustness$rb11, robustness$degree, method = "spearman")
cor.test(robustness$rb11, robustness$tl, method = "spearman")
cor.test(robustness$rb11, robustness$am, method = "spearman")
cor.test(robustness$rb11, robustness$wm, method = "spearman")
```

```{r}
#graphic creation
FI <- robustness[c(1),]
RM <- robustness[c(2),]
HF <- robustness[c(3),]
BP <- robustness[c(4),]
CC <- robustness[c(5),]
CS <- robustness[c(6),]
CV <- robustness[c(7),]
EE <- robustness[c(8),]
mean <- robustness[,c(6)]
AUCs <- c(FI[7:14], RM[7:14], HF[7:14], BP[7:14], CC[7:14], CS[7:14], CV[7:14], EE[7:14], mean)
ESlabel <- c(1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,5,5,5,5,5,5,5,5,6,6,6,6,6,6,6,6,7,7,7,7,7,7,7,7,8,8,8,8,8,8,8,8,1,2,3,4,5,6,7,8)
statlabel <- c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0)
EScor <- cbind(ESlabel, AUCs, statlabel)
EScor <- as.data.frame(EScor)
EScor$AUCs <- as.numeric(EScor$AUCs)
EScor$ESlabel <- as.character(EScor$ESlabel)
EScor$statlabel <- as.character(EScor$statlabel)
ggplot(EScor, aes(x=AUCs, y=ESlabel, color = statlabel)) + scale_color_manual(values=c("darkcyan", "black")) + geom_point(size=3) + theme_bw() + ylab(NULL) + xlab("Robustness") + theme(axis.text=element_text(size=12), axis.title=element_text(size=14))

#topological stats calc
ESmat <- as_adjacency_matrix(ESnet, sparse = FALSE, attr = NULL)
ESdegree <- degree(ESnet)
EStl <- TrophInd(Tij = t(ESmat))
nodes$ESdegree <- ESdegree
nodes$EStl <- EStl
ESmetrics <- subset(nodes, nodes$vertextype > 2)
ESmetrics <- cbind(ESmetrics[,c(1,3,4)], am, wm, robustness$rbmean, c(1,2,3,4,5,6,7,8))

#stats graphics
ESmetrics %>% mutate(ES = fct_reorder(ES, rev(c(1,2,3,4,5,6,7,8)))) %>% ggplot(aes(x=degree, y=ES)) + geom_point() + theme_bw() + ylab(NULL) + xlab("Degree")
ESmetrics %>% mutate(ES = fct_reorder(ES, rev(c(1,2,3,4,5,6,7,8)))) %>% ggplot(aes(x=tl, y=ES)) + geom_point() + theme_bw() + ylab(NULL) + xlab("Trophic level")
ESmetrics %>% mutate(ES = fct_reorder(ES, rev(c(1,2,3,4,5,6,7,8)))) %>% ggplot(aes(x=am, y=ES)) + geom_point() + theme_bw() + ylab(NULL) + xlab("Among-module connection")
ESmetrics %>% mutate(ES = fct_reorder(ES, rev(c(1,2,3,4,5,6,7,8)))) %>% ggplot(aes(x=wm, y=ES)) + geom_point() + theme_bw() + ylab(NULL) + xlab("Within-module connection")

ggplot(ESmetrics, aes(x = degree, y = robustness$rbmean)) + geom_point(size = 3) + ylim(c(0.6,.75)) +  ylab("Individual service robustness") + xlab("Degree") + theme_classic()
ggplot(ESmetrics, aes(x = tl, y = robustness$rbmean)) + geom_point(size = 3) + ylim(c(0.6,.75)) +  ylab("Individual service robustness") + xlab("Trophic level") + theme_classic()
ggplot(ESmetrics, aes(x = am, y = robustness$rbmean)) + geom_point(size = 3) + ylim(c(0.6,.75)) +  ylab("Individual service robustness") + xlab("Among-module connection") + theme_classic()
ggplot(ESmetrics, aes(x = wm, y = robustness$rbmean)) + geom_point(size = 3) + ylim(c(0.6,.75)) +  ylab("Individual service robustness") + xlab("Within-module connection") + theme_classic()

```